- id: check-podfile
  name: Check Podfile
  description: This hook makes sure Podfile is valid and Podfile.lock is up to date.
  language: script
  entry: check-podfile.sh
  types: [text]
  files: 'Podfile(.lock)?'
- id: swiftformat
  name: Swiftformat
  description: Formats Swift files using Swiftformat.
  language: system
  entry: swiftformat
  args: ['--quiet']
  types: [text]
  files: '.*\.swift$'
